version: '3.8'

services:
  # 1. ฐานข้อมูล PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: pos_postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    networks:
      - share-container-network
    restart: always

  # 2. Redis (เผื่อใช้ Caching หรือ Session ในอนาคต)
  redis:
    image: redis:alpine
    container_name: pos_redis
    ports:
      - "6379:6379"
    networks:
      - share-container-network
    restart: always

  # 3. PgAdmin (หน้าเว็บสำหรับจัดการ Database - Optional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pos_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - share-container-network

  # 4. Backend Service (NestJS)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pos_backend
    ports:
      - "3000:3000"
      - "9897:9897"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    networks:
      - share-container-network
    restart: always

volumes:
  postgres_data_v2:

networks:
  share-container-network:
    external: true
